### ISSUE TITLE
DORADO-TUFMAN-LL-Report 21 (Map – longline catch and effort by Fleet)

### ISSUE THREAD

**Issue by ManuSchneiter** [spc-ofp/tubs-web-reporting#11]
Even though the query seems to work in SSMS, the map doesn't display anything for me - something strange/wrong here

**Comment by brunodeprez** [comment]
Manu,

interesting error indeed. The problem was that the longitude was -180 to 180, so the pies were there, but you had to scroll to the left around the globe to find it. In Dorado, when maps should be displayed, the longitude should always be 0-360.

There is a function in tufman2 database to get the decimal 360 longitude called ref.GetLonD360fromLon.

Thanks!
